import { Platform, StyleSheet } from "react-native";

import { colors, spacing } from "@/theme/design";

const shadowHero = Platform.select({
  ios: {
    shadowColor: "#6B705C",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
  },
  android: {
    elevation: 3,
    shadowColor: "#000",
  },
  default: {},
});

const shadowCard = Platform.select({
  ios: {
    shadowColor: "#6B705C",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  android: {
    elevation: 3,
    shadowColor: "#000",
  },
  default: {},
});

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  listContent: {
    padding: spacing.screen,
    paddingBottom: 140,
    gap: 14,
  },
  header: {
    marginBottom: 2,
  },
  heroShadow: {
    borderRadius: 24,
    position: "relative",
    ...shadowHero,
  },
  heroAndroidShadow: {
    ...StyleSheet.absoluteFillObject,
    top: 1,
    left: -1,
    right: -1,
    bottom: -2,
    borderRadius: 24,
    backgroundColor: "#000000",
    opacity: 0.12,
  },
  heroSurface: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.8)",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    gap: 12,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  headingBlock: {
    flex: 1,
    gap: 4,
  },
  headingKicker: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.4,
    color: "#A5A58D",
  },
  heading: {
    fontSize: 28,
    fontWeight: "900",
    color: "#2D2D2A",
    letterSpacing: -0.8,
    lineHeight: 32,
  },
  subtitle: {
    color: "#6B705C",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
  },
  headerMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  headerChip: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E4D9C8",
    backgroundColor: "#F5EFE4",
  },
  headerChipText: {
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "#6B705C",
  },
  subheading: {
    fontSize: 11,
    fontWeight: "800",
    color: "#A5A58D",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  bookCreatorRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  bookInput: {
    flex: 1,
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E4D9C8",
    backgroundColor: "#FCFAF7",
    paddingHorizontal: 14,
    color: "#2D2D2A",
    fontSize: 14,
    fontWeight: "500",
  },
  createBookButtonInner: {
    paddingHorizontal: 14,
    flexDirection: "row",
    gap: 6,
  },
  createBookButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
  },
  bookErrorText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: "600",
  },
  errorText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: "600",
  },
  bookCardShadow: {
    borderRadius: 24,
    position: "relative",
    ...shadowCard,
  },
  bookAndroidShadow: {
    ...StyleSheet.absoluteFillObject,
    top: 1,
    left: -1,
    right: -1,
    bottom: -2,
    borderRadius: 24,
    backgroundColor: "#000000",
    opacity: 0.11,
  },
  bookCardSurface: {
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.85)",
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  bookCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  bookTitleBlock: {
    flex: 1,
    gap: 3,
  },
  bookEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    color: "#A5A58D",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  bookTitle: {
    fontSize: 21,
    fontWeight: "800",
    color: "#2D2D2A",
    letterSpacing: -0.5,
    lineHeight: 25,
  },
  bookArrow: {
    width: 30,
    height: 30,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(188, 108, 37, 0.2)",
    backgroundColor: "rgba(188, 108, 37, 0.09)",
  },
  bookFooterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(228, 217, 200, 0.7)",
    paddingTop: 10,
  },
  countChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E4D9C8",
    backgroundColor: "#F5EFE4",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  countChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#6B705C",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  bookFooterText: {
    flex: 1,
    textAlign: "right",
    fontSize: 12,
    fontWeight: "600",
    color: "#A5A58D",
  },
  cardPressed: {
    transform: [{ scale: 0.995 }],
    opacity: 0.95,
  },
  loader: {
    marginTop: 32,
  },
  emptyState: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(228, 217, 200, 0.8)",
    backgroundColor: "#FFFFFF",
    padding: 20,
    gap: 6,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#2D2D2A",
  },
  emptySubtitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6B705C",
  },
  recipeCardShadow: {
    borderRadius: 24,
    position: "relative",
    ...shadowCard,
  },
  recipeAndroidShadow: {
    ...StyleSheet.absoluteFillObject,
    top: 1,
    left: -1,
    right: -1,
    bottom: -2,
    borderRadius: 24,
    backgroundColor: "#000000",
    opacity: 0.11,
  },
  recipeCardSurface: {
    borderRadius: 24,
    paddingHorizontal: 5,
    paddingTop: 5,
    paddingBottom: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.8)",
    gap: 12,
  },
  recipeThumb: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: 22,
    backgroundColor: "#F5EFE4",
  },
  recipeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  recipeHeadingBlock: {
    flex: 1,
    gap: 3,
  },
  recipeEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    color: "#A5A58D",
  },
  recipeTitle: {
    fontSize: 21,
    fontWeight: "800",
    color: "#2D2D2A",
    letterSpacing: -0.6,
    lineHeight: 25,
  },
  recipeMeta: {
    flexDirection: "row",
    gap: 6,
    flexWrap: "wrap",
  },
  metaChip: {
    backgroundColor: "#F5EFE4",
    borderWidth: 1,
    borderColor: "#E4D9C8",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  metaChipAccent: {
    backgroundColor: "rgba(188, 108, 37, 0.1)",
    borderColor: "rgba(188, 108, 37, 0.2)",
  },
  metaChipText: {
    color: "#6B705C",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  metaChipTextAccent: {
    color: "#BC6C25",
  },
  actionsRow: {
    paddingTop: 10,
    marginTop: 2,
    borderTopWidth: 1,
    borderTopColor: "rgba(228, 217, 200, 0.7)",
    flexDirection: "row",
    gap: 8,
  },
  actionButtonWrapper: {
    flex: 1,
  },
  actionButtonInner: {
    flexDirection: "row",
    gap: 6,
  },
  actionButtonSoftText: {
    color: "#6B705C",
    fontSize: 13,
    fontWeight: "700",
  },
  actionButtonAccentText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
});
